version: "3.9"

networks:
  postgres:
    driver: bridge

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DBNAME}"
    volumes:
       - ./postgres:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  streamlit:
    image: scrape_app
    container_name: scrape_app
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_HOST: "postgres"
      POSTGRES_DBNAME: "${POSTGRES_DBNAME}"
    # volumes:
    #   - ./streamlit:/app
    ports:
      - "8501:8501"
    networks:
      - postgres
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8501/ || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"